version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: musify
      POSTGRES_PASSWORD: musify_secret
      POSTGRES_DB: musify-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gateway-net

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - /home/jyotirmoysaha/server/musify.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=musify
      - DB_PASSWORD=musify_secret
      - DB_DATABASE=musify-db
    depends_on:
      - db
    networks:
      - gateway-net
    volumes:
      - /home/jyotirmoysaha/musify_media:/usr/src/app/media

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=/musify-api
    depends_on:
      - api
    networks:
      - gateway-net

volumes:
  pgdata:

networks:
  gateway-net:
    external: true
