version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: spotify-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: spotify
      POSTGRES_PASSWORD: spotify_secret
      POSTGRES_DB: spotify_clone
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
