name: Deploy Musify to Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Deploy with Docker Compose
        run: |
          docker compose -p musify-final up --build -d
          
      - name: Clean up old Docker images
        run: |
          docker image prune -f
